using Xunit;

namespace PolicySearchService.IntegrationTest;

[CollectionDefinition(nameof(PolicySearchControllerFixtureCollection))]
public class PolicySearchControllerFixtureCollection: ICollectionFixture<PolicySearchControllerFixture>;